on:
  push:
    paths:
      - "cv/**"
  pull_request:
    paths:
      - "cv/**"
  workflow_dispatch:
  schedule:
    - cron: "14 14 3/5 * *"

permissions:
  contents: read

jobs:
  build_cv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: sudo .devcontainer/installTex.sh
      - run: .devcontainer/setupTex.sh
      - run: latexmk -xelatex
        working-directory: cv
      - run: "[ -f cv/cv.pdf ]"
      - uses: actions/upload-artifact@v4
        with:
          name: cv
          path: cv/cv.pdf
