on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "30 3 */4 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: awesome.yml
          name: awesome
          path: _data/awesome
      - run: npm ci
      - run: node bin/images.mjs
      - uses: actions/upload-artifact@v2
        with:
          name: images
          path: _data/images
