on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "30 3 */4 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: node bin/images.mjs
      - uses: actions/upload-artifact@v3
        with:
          name: images
          path: _data/images
