on:
  push:
    paths:
      - "src/**/*.jpg"
      - "src/**/*.jpeg"
      - "src/**/*.png"
      - "src/**/*.webp"
      - "src/**/*.avif"
      - "bin/images.mjs"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: node bin/images.mjs
      - uses: actions/upload-artifact@v3
        with:
          name: images
          path: _data/images
