on:
  push:
    paths:
      - "src/**/*.jpg"
      - "src/**/*.jpeg"
      - "src/**/*.png"
      - "src/**/*.webp"
      - "src/**/*.avif"
      - "bin/images.mjs"
  workflow_dispatch:
  schedule:
    - cron: "14 14 2/5 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "22"
      - run: npm ci
      - run: node bin/images.mjs
      - uses: actions/upload-artifact@v4
        with:
          name: images
          path: _data/images
